// Slack API client -- generated by secret-sauce
// Uses XHR from the Slack page context (same-origin) for all API calls.
// Supports multiple workspaces — auto-detects from active Slack tab or use --workspace=<ID>.

const SLACK_DOMAIN = 'app.slack.com';

// --- Tab management ---

let _tabId = null;
let _tabUrl = null;

async function findSlackTab() {
  if (_tabId) return _tabId;

  const list = await exec('playwright-cli tab-list');
  if (list.exitCode !== 0) {
    console.error('Error: Failed to list browser tabs with `playwright-cli tab-list`.');
    if (list.stderr && list.stderr.trim()) {
      console.error(list.stderr.trim());
    }
    process.exit(1);
  }
  // Match any tab on app.slack.com — handle both local and remote (follower/leader) tab IDs
  // Prefer tabs with /client/<ID>/ in the URL (actual workspace views) over login/help pages
  const lines = list.stdout.split('\n');
  let fallbackTabId = null;
  let fallbackTabUrl = null;
  for (const line of lines) {
    if (line.includes(SLACK_DOMAIN)) {
      const m = line.match(/^\[([^\]]+)\]/);
      if (m) {
        const urlMatch = line.match(/https?:\/\/\S+/);
        const url = urlMatch ? urlMatch[0] : null;
        // Prefer tabs with a workspace URL (/client/<ID>/...)
        if (url && /\/client\/[A-Z0-9]+/.test(url)) {
          _tabId = m[1];
          _tabUrl = url;
          return _tabId;
        }
        // Keep the first Slack tab as fallback
        if (!fallbackTabId) {
          fallbackTabId = m[1];
          fallbackTabUrl = url;
        }
      }
    }
  }
  // No tab with /client/ URL found — use the first Slack tab as fallback
  if (fallbackTabId) {
    _tabId = fallbackTabId;
    _tabUrl = fallbackTabUrl;
    return _tabId;
  }

  console.error('Error: No Slack tab found. Open app.slack.com in your browser and try again.');
  process.exit(1);
}

// --- Workspace resolution ---

function getActiveWorkspaceFromTabUrl() {
  if (!_tabUrl) return null;
  // URL format: https://app.slack.com/client/E23RE8G4F/C0899S7HV0E
  const m = _tabUrl.match(/\/client\/([A-Z0-9]+)/);
  return m ? m[1] : null;
}

function validateWorkspaceId(id) {
  if (!/^[A-Z0-9]+$/.test(id)) {
    console.error(`Error: Invalid workspace ID "${id}". Expected format: alphanumeric (e.g. E23RE8G4F, T06DUTYDQ).`);
    process.exit(1);
  }
  return id;
}

async function resolveWorkspace(globalFlags) {
  // 1. Explicit flag takes priority
  if (globalFlags.workspace) {
    return validateWorkspaceId(globalFlags.workspace);
  }

  // 2. Auto-detect from the active Slack tab URL
  await findSlackTab();
  const wsId = getActiveWorkspaceFromTabUrl();
  if (wsId) return wsId;

  console.error('Error: Could not determine workspace.');
  console.error('The Slack tab URL did not contain a workspace ID (expected /client/<ID>/...).');
  console.error('Use --workspace=<ID> or --ws=<ID> to specify one explicitly.');
  console.error('Run "slack workspaces" to list available workspaces.');
  process.exit(1);
}

// --- Eval helper ---
// Evaluates a JavaScript expression in the Slack browser tab and returns parsed JSON.
// Handles temp file creation, cleanup, double-encoded JSON, and error handling.

async function evalInSlackTab(expr, { fatal = true } = {}) {
  const tabId = await findSlackTab();
  const tmpFile = '/shared/.slack_eval_' + Date.now() + '.js';
  await fs.writeFile(tmpFile, expr.trim().replace(/\n/g, ' '));
  const result = await exec(`playwright-cli eval-file ${tmpFile} --tab=${tabId}`);
  await fs.rm(tmpFile).catch(async () => {
    await fs.writeFile(tmpFile, '').catch(() => {});
  });

  if (result.exitCode !== 0) {
    if (!fatal) return { ok: false, error: 'eval_failed' };
    console.error('Eval failed:', result.stderr);
    process.exit(1);
  }

  let data;
  try {
    const stdout = result.stdout.trim();
    data = JSON.parse(stdout);
    if (typeof data === 'string') data = JSON.parse(data);
    if (!data || typeof data !== 'object') throw new Error('API response was not an object');
  } catch (e) {
    if (!fatal) return { ok: false, error: 'parse_failed' };
    console.error('Failed to parse API response:', result.stdout.substring(0, 200));
    process.exit(1);
  }

  return data;
}

// --- API helper ---
// Executes Slack Web API calls via XHR from the Slack page context.
// This ensures same-origin cookies are included and the xoxc token works.

async function slackApi(method, params, workspaceId, { fatal = true } = {}) {
  // Build the param entries as a JSON array to pass into eval
  const paramEntries = Object.entries(params);
  const paramJson = JSON.stringify(paramEntries);

  // The eval expression: extract token from localStorage, build XHR, return response
  const expr = `
(async () => {
  let token;
  try {
    const rawCfg = localStorage.getItem('localConfig_v2');
    const cfg = JSON.parse(rawCfg);
    if (!cfg || !cfg.teams || !cfg.teams['${workspaceId}'] || !cfg.teams['${workspaceId}'].token) {
      return JSON.stringify({ ok: false, error: 'token_not_found', detail: 'No token for workspace ${workspaceId}' });
    }
    token = cfg.teams['${workspaceId}'].token;
  } catch (e) {
    return JSON.stringify({ ok: false, error: 'token_not_found', detail: 'Failed to parse localConfig_v2' });
  }
  const params = new URLSearchParams();
  params.append('token', token);
  const entries = ${paramJson};
  for (const [k, v] of entries) {
    params.append(k, String(v));
  }
  return new Promise((resolve) => {
    const xhr = new XMLHttpRequest();
    xhr.open('POST', '/api/${method}', true);
    xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
    xhr.withCredentials = true;
    xhr.onload = () => resolve(xhr.responseText);
    xhr.onerror = () => resolve(JSON.stringify({ ok: false, error: 'xhr_error' }));
    xhr.send(params.toString());
  });
})()
  `;

  const data = await evalInSlackTab(expr, { fatal });

  if (!data.ok) {
    if (data.error === 'invalid_auth' || data.error === 'token_not_found') {
      if (!fatal) return data;
      console.error('Auth failed. Log into Slack at app.slack.com in your browser and try again.');
      if (data.detail) console.error('Detail:', data.detail);
      process.exit(1);
    }
    if (data.error === 'ratelimited') {
      if (!fatal) return data;
      console.error('Rate limited by Slack. Wait a moment and try again.');
      process.exit(1);
    }
  }

  return data;
}

// --- Argument parsing ---

function parseArgs(args) {
  const flags = {};
  const positional = [];
  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    if (arg.startsWith('--')) {
      const eq = arg.indexOf('=');
      if (eq > 0) {
        flags[arg.substring(2, eq)] = arg.substring(eq + 1);
      } else {
        const name = arg.substring(2);
        // Peek at next arg: if it exists and isn't a flag, treat it as the value
        if (i + 1 < args.length && !args[i + 1].startsWith('--')) {
          flags[name] = args[++i];
        } else {
          flags[name] = true;
        }
      }
    } else {
      positional.push(arg);
    }
  }
  return { flags, positional };
}

// --- Formatters ---

function formatTimestamp(ts) {
  const d = new Date(parseFloat(ts) * 1000);
  return d.toISOString().replace('T', ' ').replace(/\.\d+Z$/, ' UTC');
}

function formatMessage(msg) {
  const name = msg.user_profile?.display_name || msg.user_profile?.real_name || msg.user || 'unknown';
  const time = formatTimestamp(msg.ts);
  const text = msg.text || '';
  const thread = msg.reply_count ? ` [${msg.reply_count} replies]` : '';
  return `[${time}] ${name}: ${text}${thread}`;
}

// --- Commands ---

const commands = {

  async workspaces(args, globalFlags) {
    const tabId = await findSlackTab();
    const activeWsId = getActiveWorkspaceFromTabUrl();

    // Fetch all teams from localConfig_v2 (id, name, domain, url — NOT the token)
    const expr = `
(async () => {
  try {
    const rawCfg = localStorage.getItem('localConfig_v2');
    const cfg = JSON.parse(rawCfg);
    if (!cfg || !cfg.teams) return JSON.stringify({ ok: false, error: 'no_teams' });
    const teams = [];
    for (const [id, team] of Object.entries(cfg.teams)) {
      teams.push({ id, name: team.name || '', domain: team.domain || '', url: team.url || '' });
    }
    return JSON.stringify({ ok: true, teams });
  } catch (e) {
    return JSON.stringify({ ok: false, error: e.message });
  }
})()
    `.trim().replace(/\n/g, ' ');

    const tmpFile = '/shared/.slack_eval_' + Date.now() + '.js';
    await fs.writeFile(tmpFile, expr);
    const result = await exec(`playwright-cli eval-file ${tmpFile} --tab=${tabId}`);
    await fs.rm(tmpFile).catch(async () => {
      await fs.writeFile(tmpFile, '').catch(() => {});
    });

    if (result.exitCode !== 0) {
      console.error('Eval failed:', result.stderr);
      process.exit(1);
    }

    let data;
    try {
      const stdout = result.stdout.trim();
      data = JSON.parse(stdout);
      if (typeof data === 'string') data = JSON.parse(data);
    } catch (e) {
      console.error('Failed to parse response:', result.stdout.substring(0, 200));
      process.exit(1);
    }

    if (!data.ok) {
      console.error('Error:', data.error);
      process.exit(1);
    }

    const teams = data.teams;
    if (!teams || teams.length === 0) {
      console.log('No workspaces found in localConfig_v2.');
      return;
    }

    // Calculate column widths for alignment
    const idWidth = Math.max(4, ...teams.map(t => t.id.length));
    const nameWidth = Math.max(4, ...teams.map(t => t.name.length));

    console.log('Workspaces:\n');
    for (const t of teams) {
      const host = t.url ? t.url.replace(/^https?:\/\//, '').replace(/\/$/, '') : t.domain + '.slack.com';
      const active = t.id === activeWsId ? '  *' : '';
      console.log(`  ${t.id.padEnd(idWidth)}  ${t.name.padEnd(nameWidth)}  ${host}${active}`);
    }

    if (activeWsId) {
      console.log(`\n* = active workspace (from tab URL)`);
    }
  },

  async history(args, globalFlags) {
    const { flags, positional } = parseArgs(args);
    const channel = positional[0];
    if (!channel) {
      console.error('Usage: slack history <channel_id> [--limit=N]');
      process.exit(1);
    }
    const wsId = await resolveWorkspace(globalFlags);
    const limit = flags.limit || '20';
    const params = { channel, limit };
    if (flags.oldest) params.oldest = flags.oldest;
    if (flags.latest) params.latest = flags.latest;
    if (flags.cursor) params.cursor = flags.cursor;

    const data = await slackApi('conversations.history', params, wsId);
    if (!data.ok) {
      console.error('Error:', data.error);
      process.exit(1);
    }

    // Print messages in chronological order (API returns newest first)
    const msgs = data.messages.reverse();
    for (const msg of msgs) {
      console.log(formatMessage(msg));
    }
    if (data.has_more) {
      console.log(`\n--- More messages available. Use --cursor=${data.response_metadata?.next_cursor} ---`);
    }
  },

  async post(args, globalFlags) {
    const { flags, positional } = parseArgs(args);
    const channel = positional[0];
    // Filter out shell redirect tokens (e.g. 2>&1, >&2, 2>/dev/null) that leak
    // through when scoops call `exec('slack post ... 2>&1')` without proper quoting
    const shellRedirectRe = /^[012]?>{1,2}&?[012]?$|^[012]?>(?:\/\S+)$/;
    const message = positional.slice(1).filter(t => !shellRedirectRe.test(t)).join(' ');

    if (!channel || !message) {
      console.error('Usage: slack post <channel_or_user_id> <message> [--thread_ts=TS]');
      console.error('Accepts a conversation ID (C.../G.../D...), or user ID (U.../W... — opens a DM automatically).');
      process.exit(1);
    }

    const wsId = await resolveWorkspace(globalFlags);

    // Resolve channel: if it looks like a user ID (U/W prefix), open a DM first
    let targetChannel = channel;
    if (/^[UW][A-Z0-9]+$/.test(channel)) {
      const dmData = await slackApi('conversations.open', { users: channel, return_im: 'true' }, wsId);
      if (!dmData.ok) {
        console.error(`Error opening DM with ${channel}:`, dmData.error);
        process.exit(1);
      }
      targetChannel = dmData.channel.id;
    }

    // Convert non-Slack emoji shortcodes to Unicode before sending.
    // Layer 1: static map (emoji-map.json) — 2,100+ entries from iamcal/emoji-data + Gemoji aliases.
    // Layer 2: workspace custom emoji from emoji.list API (cached for 1 hour in emoji-cache.json).
    // Unknown shortcodes that aren't in either map pass through unchanged.
    let emojiMap = {};
    try {
      emojiMap = JSON.parse(await fs.readFile('/workspace/skills/slack/scripts/emoji-map.json', 'utf8'));
    } catch (e) {
      // static map unavailable — continue
    }
    // Merge workspace custom emoji (cached, refreshed every hour)
    try {
      const cacheFile = '/workspace/skills/slack/scripts/emoji-cache.json';
      let cache = null;
      try {
        cache = JSON.parse(await fs.readFile(cacheFile, 'utf8'));
      } catch (_) {}
      const now = Date.now();
      const TTL = 60 * 60 * 1000; // 1 hour
      if (!cache || !cache.ts || (now - cache.ts) > TTL) {
        // Fetch fresh custom emoji from Slack API
        const emojiData = await slackApi('emoji.list', {}, wsId, { fatal: false });
        if (emojiData && emojiData.ok && emojiData.emoji) {
          // Custom emoji values are either URLs (uploaded images) or "alias:other_name"
          // For aliases, resolve to the aliased name's Unicode if possible
          const customMap = {};
          for (const [name, val] of Object.entries(emojiData.emoji)) {
            const key = `:${name}:`;
            if (val.startsWith('alias:')) {
              // It's an alias — resolve to Unicode via the static map if possible
              const aliasKey = `:${val.slice(6)}:`;
              if (emojiMap[aliasKey]) customMap[key] = emojiMap[aliasKey];
              // else leave unmapped — Slack renders custom aliases natively
            }
            // URL entries are uploaded images — Slack renders them natively, no conversion needed
          }
          cache = { ts: now, map: customMap };
          await fs.writeFile(cacheFile, JSON.stringify(cache)).catch(() => {});
        }
      }
      if (cache && cache.map) Object.assign(emojiMap, cache.map);
    } catch (e) {
      // custom emoji cache unavailable — continue with static map only
    }
    const unresolved = [];
    const sanitizedMessage = message.replace(/:[a-z0-9_+-]+:/g, (match) => {
      if (emojiMap[match]) return emojiMap[match];
      unresolved.push(match);
      return match;
    });
    if (unresolved.length > 0) {
      console.error(`Error: emoji shortcode(s) could not be resolved: ${unresolved.join(', ')}`);
      console.error(`Please resend the message without those emoji shortcodes.`);
      process.exit(1);
    }

    const params = { channel: targetChannel, text: sanitizedMessage };
    if (flags.thread_ts) params.thread_ts = flags.thread_ts;

    const data = await slackApi('chat.postMessage', params, wsId);
    if (!data.ok) {
      console.error('Error:', data.error);
      process.exit(1);
    }

    console.log(`Message sent to ${targetChannel} at ${formatTimestamp(data.ts)}`);
    if (targetChannel !== channel) {
      console.log(`  (DM opened with user ${channel})`);
    }
    if (data.message) {
      console.log(`Text: ${data.message.text}`);
    }
  },

  async channels(args, globalFlags) {
    const { flags } = parseArgs(args);
    const query = flags.search || flags.query || flags.q || '';

    if (!query) {
      console.error('Usage: slack channels --search=<term>');
      console.error('Enterprise grid requires a search term for channel discovery.');
      process.exit(1);
    }

    const wsId = await resolveWorkspace(globalFlags);
    const count = flags.limit || '20';
    const page = flags.page || '1';

    const data = await slackApi('search.modules', {
      query,
      module: 'channels',
      count,
      page,
    }, wsId);

    if (!data.ok) {
      console.error('Error:', data.error);
      process.exit(1);
    }

    if (!data.items || data.items.length === 0) {
      console.log('No channels found.');
      return;
    }

    console.log(`Found ${data.pagination?.total_count || data.items.length} channels:\n`);
    for (const ch of data.items) {
      const members = ch.member_count != null ? ` (${ch.member_count} members)` : '';
      const purpose = ch.purpose?.value ? ` — ${ch.purpose.value}` : '';
      const member = ch.is_member ? ' *' : '';
      console.log(`  ${ch.id}  #${ch.name}${members}${purpose}${member}`);
    }

    if (data.pagination && data.pagination.page_count > data.pagination.page) {
      console.log(`\n--- Page ${data.pagination.page} of ${data.pagination.page_count}. Use --page=${data.pagination.page + 1} for more. ---`);
    }
  },

  async thread(args, globalFlags) {
    const { flags, positional } = parseArgs(args);
    const channel = positional[0];
    const threadTs = positional[1];

    if (!channel || !threadTs) {
      console.error('Usage: slack thread <channel_id> <thread_ts> [--limit=N]');
      process.exit(1);
    }

    const wsId = await resolveWorkspace(globalFlags);
    const limit = flags.limit || '50';
    const params = { channel, ts: threadTs, limit };
    if (flags.cursor) params.cursor = flags.cursor;

    const data = await slackApi('conversations.replies', params, wsId);
    if (!data.ok) {
      console.error('Error:', data.error);
      process.exit(1);
    }

    for (const msg of data.messages) {
      console.log(formatMessage(msg));
    }
    if (data.has_more) {
      console.log(`\n--- More replies available. Use --cursor=${data.response_metadata?.next_cursor} ---`);
    }
  },

  async user(args, globalFlags) {
    const { positional } = parseArgs(args);
    const userId = positional[0];

    if (!userId) {
      console.error('Usage: slack user <user_id>');
      process.exit(1);
    }

    const wsId = await resolveWorkspace(globalFlags);
    const data = await slackApi('users.info', { user: userId }, wsId);
    if (!data.ok) {
      console.error('Error:', data.error);
      process.exit(1);
    }

    const u = data.user;
    const p = u.profile || {};
    console.log(`User: ${u.real_name || u.name}`);
    console.log(`  ID:           ${u.id}`);
    console.log(`  Username:     ${u.name}`);
    console.log(`  Display name: ${p.display_name || '(none)'}`);
    console.log(`  Title:        ${p.title || '(none)'}`);
    console.log(`  Timezone:     ${u.tz || '(unknown)'}`);
    console.log(`  Is bot:       ${u.is_bot}`);
    if (p.status_text) {
      console.log(`  Status:       ${p.status_emoji || ''} ${p.status_text}`);
    }
  },

  async info(args, globalFlags) {
    const { positional } = parseArgs(args);
    const channel = positional[0];

    if (!channel) {
      console.error('Usage: slack info <channel_id>');
      process.exit(1);
    }

    const wsId = await resolveWorkspace(globalFlags);
    const data = await slackApi('conversations.info', { channel }, wsId);
    if (!data.ok) {
      console.error('Error:', data.error);
      process.exit(1);
    }

    const ch = data.channel;
    console.log(`Channel: #${ch.name || ch.id}`);
    console.log(`  ID:       ${ch.id}`);
    if (ch.name) console.log(`  Name:     ${ch.name}`);
    if (ch.purpose?.value) console.log(`  Purpose:  ${ch.purpose.value}`);
    if (ch.topic?.value) console.log(`  Topic:    ${ch.topic.value}`);
    if (ch.num_members != null) console.log(`  Members:  ${ch.num_members}`);
    console.log(`  Archived: ${ch.is_archived || false}`);
    if (ch.is_im) console.log(`  Type:     DM (with user ${ch.user})`);
    else if (ch.is_mpim) console.log(`  Type:     Group DM`);
    else if (ch.is_private) console.log(`  Type:     Private channel`);
    else console.log(`  Type:     Public channel`);
  },

  async slackbot(args, globalFlags) {
    const wsId = await resolveWorkspace(globalFlags);
    const data = await slackApi('conversations.open', {
      users: 'USLACKBOT',
      return_im: 'true',
    }, wsId);

    if (!data.ok) {
      console.error('Error:', data.error);
      process.exit(1);
    }

    const ch = data.channel;
    console.log(`Slackbot DM channel: ${ch.id}`);
    if (data.already_open) console.log('  (already open)');
  },

  async watch(args, globalFlags) {
    const { flags, positional } = parseArgs(args);
    const channel = positional[0];
    const scoop = flags.scoop;
    const threadTs = flags.thread || null;

    if (!channel || !scoop) {
      console.error('Usage: slack watch <channel_id> --scoop=<name> [--thread=<ts>] [--force]');
      process.exit(1);
    }

    const watchId = threadTs ? `${channel}-${threadTs}` : channel;
    const stateFile = `/workspace/skills/slack/.watch-${watchId}.json`;

    // Check for existing watch
    try {
      const existing = JSON.parse(await fs.readFile(stateFile, 'utf8'));
      if (!flags.force) {
        console.error(`Already watching ${watchId} (scoop: ${existing.scoop}).`);
        console.error('Use --force to replace.');
        process.exit(1);
      }
      // Clean up old webhook
      if (existing.webhookId) {
        await exec(`slicc webhook delete ${existing.webhookId}`).catch(() => {});
      }
    } catch (_) {
      // No existing watch — proceed
    }

    // Create SLICC webhook routed to target scoop
    const whResult = await exec(`slicc webhook create --scoop=${scoop} --format=json`);
    if (whResult.exitCode !== 0) {
      console.error('Failed to create webhook:', whResult.stderr);
      process.exit(1);
    }
    let webhook;
    try {
      webhook = JSON.parse(whResult.stdout.trim());
    } catch (e) {
      console.error('Failed to parse webhook response:', whResult.stdout.substring(0, 200));
      process.exit(1);
    }

    // Save watch state
    const state = {
      watchId,
      channel,
      thread_ts: threadTs,
      scoop,
      webhookId: webhook.id,
      webhookUrl: webhook.url,
      createdAt: new Date().toISOString(),
    };
    await fs.writeFile(stateFile, JSON.stringify(state, null, 2));

    // Inject interceptor with the full watch set so all watches stay active
    const allStates = await loadAllWatchStates();
    try {
      await injectWsInterceptor(allStates);
    } catch (e) {
      // Roll back: remove state file and delete webhook on injection failure
      await fs.rm(stateFile).catch(() => {});
      await exec(`slicc webhook delete ${webhook.id}`).catch(() => {});
      console.error('Failed to inject interceptor — watch rolled back:', e.message || e);
      process.exit(1);
    }

    console.log(`Watching ${watchId} → scoop "${scoop}"`);
    console.log(`  Webhook: ${webhook.id}`);
    if (threadTs) console.log(`  Thread: ${threadTs}`);
  },

  async unwatch(args, globalFlags) {
    const { flags, positional } = parseArgs(args);
    const channel = positional[0];
    const threadTs = flags.thread || null;

    if (!channel) {
      console.error('Usage: slack unwatch <channel_id> [--thread=<ts>]');
      process.exit(1);
    }

    const watchId = threadTs ? `${channel}-${threadTs}` : channel;
    const stateFile = `/workspace/skills/slack/.watch-${watchId}.json`;

    let state;
    try {
      state = JSON.parse(await fs.readFile(stateFile, 'utf8'));
    } catch (_) {
      console.error(`No active watch for ${watchId}.`);
      process.exit(1);
    }

    // Delete webhook
    if (state.webhookId) {
      await exec(`slicc webhook delete ${state.webhookId}`).catch(() => {});
    }

    // Remove state file
    await fs.rm(stateFile).catch(() => {});

    // Reinject with remaining watches so the in-page interceptor is updated
    const remainingStates = await loadAllWatchStates();
    if (remainingStates.length > 0) {
      await injectWsInterceptor(remainingStates).catch(() => {});
    } else {
      // No watches left — clear the in-page watch list
      await injectWsInterceptor([]).catch(() => {});
    }

    console.log(`Stopped watching ${watchId} (was → scoop "${state.scoop}").`);
  },

  async watches(args, globalFlags) {
    const globResult = await exec('ls /workspace/skills/slack/.watch-*.json 2>/dev/null');
    if (globResult.exitCode !== 0 || !globResult.stdout.trim()) {
      console.log('No active watches.');
      return;
    }

    const files = globResult.stdout.trim().split('\n');
    console.log(`Active watches (${files.length}):\n`);
    for (const file of files) {
      try {
        const state = JSON.parse(await fs.readFile(file.trim(), 'utf8'));
        const thread = state.thread_ts ? ` thread=${state.thread_ts}` : '';
        console.log(`  ${state.watchId}${thread} → scoop "${state.scoop}" (webhook: ${state.webhookId})`);
        console.log(`    Created: ${state.createdAt}`);
      } catch (_) {
        console.log(`  (corrupt state file: ${file})`);
      }
    }
  },

  async reinject(args, globalFlags) {
    const globResult = await exec('ls /workspace/skills/slack/.watch-*.json 2>/dev/null');
    if (globResult.exitCode !== 0 || !globResult.stdout.trim()) {
      console.log('No active watches to reinject.');
      return;
    }

    const files = globResult.stdout.trim().split('\n');
    const states = [];
    for (const file of files) {
      try {
        states.push(JSON.parse(await fs.readFile(file.trim(), 'utf8')));
      } catch (_) {}
    }

    if (states.length === 0) {
      console.log('No valid watch states found.');
      return;
    }

    await injectWsInterceptor(states);
    console.log(`Re-injected interceptor with ${states.length} watch(es).`);
  },

  async activity(args, globalFlags) {
    const { flags } = parseArgs(args);
    const wsId = await resolveWorkspace(globalFlags);
    const limit = flags.limit || '20';
    const unreadOnly = flags.unread === true || flags.unread === 'true';
    const cursor = flags.cursor || null;

    // Map --type filter to activity.feed types
    const typeMap = {
      all: 'generic_system_alert,bot_dm_bundle,at_user,at_user_group,at_channel,at_everyone,unjoined_channel_mention,thread_v2,message_reaction,internal_channel_invite,external_channel_invite,list_record_edited,list_record_assigned,list_user_mentioned,list_todo_notification,list_approval_request,list_approval_reviewed',
      admin: 'generic_system_alert',
      mentions: 'at_user,at_user_group,at_channel,at_everyone,unjoined_channel_mention',
      threads: 'thread_v2',
      reactions: 'message_reaction',
      invites: 'internal_channel_invite,external_channel_invite',
      apps: 'bot_dm_bundle',
    };
    const typeFilter = flags.type || 'all';
    const types = typeMap[typeFilter];
    if (!types) {
      console.error(`Unknown --type "${typeFilter}". Valid types: ${Object.keys(typeMap).join(', ')}`);
      process.exit(1);
    }

    const params = {
      limit,
      types,
      mode: 'chrono_reads_and_unreads',
      archive_only: 'false',
      unread_only: String(unreadOnly),
      priority_only: 'false',
    };
    if (cursor) params.cursor = cursor;

    const data = await slackApi('activity.feed', params, wsId);
    if (!data.ok) {
      console.error('Error:', data.error);
      process.exit(1);
    }

    if (!data.items || data.items.length === 0) {
      console.log('No activity items found.');
      return;
    }

    // Collect user and channel IDs to resolve in batch
    const userIds = new Set();
    const channelIds = new Set();
    for (const item of data.items) {
      const i = item.item;
      if (i.type === 'generic_system_alert') {
        for (const b of (i.generic_system_alert_payload?.blocks || [])) {
          for (const el of (b.elements || [])) {
            for (const sub of (el.elements || [])) {
              if (sub.type === 'user') userIds.add(sub.user_id);
              if (sub.type === 'channel') channelIds.add(sub.channel_id);
            }
          }
        }
      }
      if (i.message?.author_user_id) userIds.add(i.message.author_user_id);
      if (i.message?.channel) channelIds.add(i.message.channel);
      if (i.invite_info?.channel_id) channelIds.add(i.invite_info.channel_id);
      if (i.invite_info?.inviter_user_id) userIds.add(i.invite_info.inviter_user_id);
    }

    // Resolve names (best-effort, non-fatal — rate limits or errors won't kill the command)
    const userNames = {};
    for (const uid of userIds) {
      const u = await slackApi('users.info', { user: uid }, wsId, { fatal: false });
      if (u.ok) userNames[uid] = u.user.real_name || u.user.name || uid;
    }
    const channelNames = {};
    for (const cid of channelIds) {
      const c = await slackApi('conversations.info', { channel: cid }, wsId, { fatal: false });
      if (c.ok) channelNames[cid] = '#' + (c.channel.name || cid);
    }

    function resolveName(uid) { return userNames[uid] || uid; }
    function resolveChannel(cid) { return channelNames[cid] || cid; }

    // For bot_dm_bundle items, fetch the latest message from the DM channel
    const botDmMessages = {};
    for (const item of data.items) {
      const i = item.item;
      if (i.type === 'bot_dm_bundle') {
        const ch = i.bundle_info?.payload?.message?.channel;
        if (ch && !botDmMessages[ch]) {
          {
            const hist = await slackApi('conversations.history', { channel: ch, limit: '5' }, wsId, { fatal: false });
            if (hist.ok && hist.messages?.length > 0) {
              // Get latest messages, most recent first
              botDmMessages[ch] = hist.messages.slice(0, 3).map(m => {
                const name = m.bot_profile?.name || m.username || m.user || 'bot';
                let text = m.text || '';
                // Compact multi-line text
                text = text.replace(/\n+/g, ' ').substring(0, 200);
                return `${name}: ${text}`;
              });
            }
          }
        }
      }
    }

    // Format and print
    for (const item of data.items) {
      const i = item.item;
      const ts = formatTimestamp(item.feed_ts);
      const unread = item.is_unread ? ' *' : '';

      if (i.type === 'generic_system_alert') {
        const payload = i.generic_system_alert_payload || {};
        const texts = [];
        for (const b of (payload.blocks || [])) {
          for (const el of (b.elements || [])) {
            for (const sub of (el.elements || [])) {
              if (sub.type === 'text') texts.push(sub.text);
              if (sub.type === 'user') texts.push(resolveName(sub.user_id));
              if (sub.type === 'channel') texts.push(resolveChannel(sub.channel_id));
              if (sub.type === 'link') texts.push(sub.text || sub.url);
            }
          }
        }
        console.log(`[${ts}] ADMIN: ${texts.join('')}${unread}`);

      } else if (i.type === 'at_user' || i.type === 'at_user_group') {
        const author = resolveName(i.message?.author_user_id);
        const ch = resolveChannel(i.message?.channel);
        console.log(`[${ts}] @mention by ${author} in ${ch}${unread}`);

      } else if (i.type === 'at_channel' || i.type === 'at_everyone') {
        const author = resolveName(i.message?.author_user_id);
        const ch = resolveChannel(i.message?.channel);
        console.log(`[${ts}] @${i.type === 'at_channel' ? 'channel' : 'everyone'} by ${author} in ${ch}${unread}`);

      } else if (i.type === 'unjoined_channel_mention') {
        console.log(`[${ts}] Mentioned in unjoined channel${unread}`);

      } else if (i.type === 'internal_channel_invite') {
        const inviter = resolveName(i.invite_info?.inviter_user_id);
        const ch = resolveChannel(i.invite_info?.channel_id);
        console.log(`[${ts}] Invited to ${ch} by ${inviter}${unread}`);

      } else if (i.type === 'external_channel_invite') {
        console.log(`[${ts}] Slack Connect invite${unread}`);

      } else if (i.type === 'bot_dm_bundle') {
        const ch = i.bundle_info?.payload?.message?.channel;
        const count = i.bundle_info?.unread_count ?? '?';
        const msgs = botDmMessages[ch];
        if (msgs && msgs.length > 0) {
          console.log(`[${ts}] App DM (${count} unread): ${msgs[0].substring(0, 200)}${unread}`);
          for (const m of msgs.slice(1)) {
            console.log(`         ${m.substring(0, 200)}`);
          }
        } else {
          console.log(`[${ts}] App DM (${count} unread)${unread}`);
        }

      } else if (i.type === 'thread_v2') {
        console.log(`[${ts}] Thread reply${unread}`);

      } else if (i.type === 'message_reaction') {
        console.log(`[${ts}] Reaction${unread}`);

      } else {
        console.log(`[${ts}] ${i.type}${unread}`);
      }
    }

    if (data.response_metadata?.next_cursor) {
      console.log(`\n--- More items available. Use --cursor=${data.response_metadata.next_cursor} ---`);
    }
  },

  async pending(args, globalFlags) {
    const { flags } = parseArgs(args);
    const wsId = await resolveWorkspace(globalFlags);
    const maxPages = parseInt(flags.pages || '10', 10);
    const format = flags.json ? 'json' : 'table';

    // Resolve Slackbot DM channel
    let channel = flags.channel;
    if (!channel) {
      const sb = await slackApi('conversations.open', { users: 'USLACKBOT', return_im: 'true' }, wsId);
      if (!sb.ok) { console.error('Error: Could not resolve Slackbot DM channel.'); process.exit(1); }
      channel = sb.channel.id;
    }

    // Page through the Slackbot DM looking for messages with action buttons
    let cursor = null;
    const pending = [];

    for (let page = 0; page < maxPages; page++) {
      const params = { channel, limit: '100' };
      if (cursor) params.cursor = cursor;

      const hist = await slackApi('conversations.history', params, wsId);
      if (!hist.ok) {
        console.error('Error fetching history:', hist.error);
        process.exit(1);
      }

      for (const msg of hist.messages) {
        const text = msg.text || '';
        const attachText = (msg.attachments || []).map(a => (a.text || '') + (a.fallback || '')).join(' ');
        const allText = text + ' ' + attachText;

        // Only look at invite/approval messages
        if (!allText.includes('requested to invite') &&
            !allText.includes('Request to join') &&
            !allText.includes('Request to add')) continue;

        // Skip already-processed
        const isProcessed = allText.includes('approved') || allText.includes('white_check_mark') ||
                            allText.includes('denied') || allText.includes('no_entry_sign') ||
                            allText.includes('Declined') || allText.includes('joined the workspace');
        if (isProcessed) continue;

        // Must have action buttons
        const hasActions = (msg.attachments || []).some(a => a.actions && a.actions.length > 0);
        if (!hasActions) continue;

        // Parse details
        let requestType = 'unknown';
        let invitee = '';
        let org = '';
        let channelName = '';
        let email = '';
        let reason = '';

        if (text.includes('Request to join')) requestType = 'join';
        else if (text.includes('Request to add')) requestType = 'add';
        else if (text.includes('requested to invite')) requestType = 'invite';

        const addMatch = text.match(/invited \*(.+?)\*/);
        if (addMatch) invitee = addMatch[1];

        const joinMatch = text.match(/<@(\w+)> was invited to join/);
        if (joinMatch) invitee = joinMatch[1];

        const orgMatch = text.match(/from (.+?) to join/);
        if (orgMatch) org = orgMatch[1];
        const joinOrgMatch = text.match(/join \*(.+?)'s\*/);
        if (joinOrgMatch) org = joinOrgMatch[1];

        for (const att of (msg.attachments || [])) {
          const at = (att.text || '') + ' ' + (att.fallback || '');
          const emailMatch = at.match(/\*Email\*:\s*<mailto:([^|]+)\|/);
          if (emailMatch) email = emailMatch[1];
          const chMatch = at.match(/\*Channel:\*\s*<#\w+\|([^>]+)>/);
          if (chMatch) channelName = chMatch[1];
          const chMatch2 = at.match(/\*Channel\*\n(.+)/);
          if (chMatch2 && !channelName) channelName = chMatch2[1].trim();
          const reasonMatch = at.match(/\*Reason for Request\*:\n(.+)/);
          if (reasonMatch) reason = reasonMatch[1].trim();
        }

        // Clean up Slack markup from channel names
        channelName = channelName.replace(/<#\w+\|([^>]+)>/g, '#$1');

        pending.push({
          ts: msg.ts,
          date: new Date(parseFloat(msg.ts) * 1000).toISOString().split('T')[0],
          type: requestType,
          invitee: invitee || '?',
          org: org || '',
          channel: channelName || '(private)',
          email: email || '',
          reason: reason || '',
        });
      }

      if (!hist.has_more || !hist.response_metadata?.next_cursor) break;
      cursor = hist.response_metadata.next_cursor;
    }

    if (pending.length === 0) {
      console.log('No pending approval requests found.');
      return;
    }

    if (format === 'json') {
      console.log(JSON.stringify(pending, null, 2));
      return;
    }

    // Table output
    console.log(`Pending approval requests (${pending.length}):\n`);

    // Calculate column widths
    const typeW = Math.max(4, ...pending.map(p => p.type.length));
    const invW = Math.min(25, Math.max(7, ...pending.map(p => p.invitee.length)));
    const orgW = Math.min(25, Math.max(4, ...pending.map(p => p.org.length)));
    const chW = Math.min(30, Math.max(7, ...pending.map(p => p.channel.length)));

    console.log(`  ${'Date'.padEnd(12)}${'Type'.padEnd(typeW + 2)}${'Invitee'.padEnd(invW + 2)}${'From'.padEnd(orgW + 2)}${'Channel'.padEnd(chW + 2)}Timestamp`);
    console.log(`  ${'─'.repeat(12)}${'─'.repeat(typeW + 2)}${'─'.repeat(invW + 2)}${'─'.repeat(orgW + 2)}${'─'.repeat(chW + 2)}${'─'.repeat(22)}`);

    for (const p of pending) {
      const inv = p.invitee.length > invW ? p.invitee.substring(0, invW - 1) + '…' : p.invitee;
      const o = p.org.length > orgW ? p.org.substring(0, orgW - 1) + '…' : p.org;
      const ch = p.channel.length > chW ? p.channel.substring(0, chW - 1) + '…' : p.channel;
      console.log(`  ${p.date.padEnd(12)}${p.type.padEnd(typeW + 2)}${inv.padEnd(invW + 2)}${o.padEnd(orgW + 2)}${ch.padEnd(chW + 2)}${p.ts}`);
    }

    console.log(`\nTo act on a request:`);
    console.log(`  slack approve <timestamp>`);
    console.log(`  slack deny <timestamp>`);
  },

  async approve(args, globalFlags) {
    const { flags, positional } = parseArgs(args);
    const messageTs = positional[0];
    if (!messageTs) {
      console.error('Usage: slack approve <message_ts> [--channel=<id>]');
      console.error('Approves an interactive action button (e.g. Slack Connect invite request).');
      console.error('The message_ts is the timestamp of the Slackbot notification message.');
      process.exit(1);
    }
    const wsId = await resolveWorkspace(globalFlags);
    let channel = flags.channel;
    if (!channel) {
      const sb = await slackApi('conversations.open', { users: 'USLACKBOT', return_im: 'true' }, wsId);
      if (!sb.ok) { console.error('Error: Could not resolve Slackbot DM channel.'); process.exit(1); }
      channel = sb.channel.id;
    }
    await executeAttachmentAction(wsId, channel, messageTs, 'approve');
  },

  async deny(args, globalFlags) {
    const { flags, positional } = parseArgs(args);
    const messageTs = positional[0];
    if (!messageTs) {
      console.error('Usage: slack deny <message_ts> [--channel=<id>]');
      console.error('Denies an interactive action button (e.g. Slack Connect invite request).');
      console.error('The message_ts is the timestamp of the Slackbot notification message.');
      process.exit(1);
    }
    const wsId = await resolveWorkspace(globalFlags);
    let channel = flags.channel;
    if (!channel) {
      const sb = await slackApi('conversations.open', { users: 'USLACKBOT', return_im: 'true' }, wsId);
      if (!sb.ok) { console.error('Error: Could not resolve Slackbot DM channel.'); process.exit(1); }
      channel = sb.channel.id;
    }
    await executeAttachmentAction(wsId, channel, messageTs, 'deny');
  },

  async monday(args, globalFlags) {
    // --- Flag parsing ---
    function parseMondayFlags(args) {
      const flags = { limit: 50, depth: 5, date: '7d' };
      for (let i = 0; i < args.length; i++) {
        if (args[i] === '--limit' && args[i+1]) flags.limit = parseInt(args[i+1]);
        if (args[i] === '--depth' && args[i+1]) flags.depth = parseInt(args[i+1]);
        if (args[i] === '--date' && args[i+1]) flags.date = args[i+1];
        // Also support --limit=N style
        if (args[i].startsWith('--limit=')) flags.limit = parseInt(args[i].split('=')[1]);
        if (args[i].startsWith('--depth=')) flags.depth = parseInt(args[i].split('=')[1]);
        if (args[i].startsWith('--date=')) flags.date = args[i].split('=')[1];
      }
      return flags;
    }

    const mFlags = parseMondayFlags(args);

    // Parse --date into a Unix timestamp (seconds) for the oldest cutoff
    function dateToOldest(dateStr) {
      const m = dateStr.match(/^(\d+)([dwh])$/);
      if (!m) return Math.floor(Date.now() / 1000) - 7 * 86400; // default 7d
      const n = parseInt(m[1]);
      const unit = m[2];
      const multiplier = unit === 'w' ? 7 * 86400 : unit === 'h' ? 3600 : 86400;
      return Math.floor(Date.now() / 1000) - n * multiplier;
    }
    const oldest = dateToOldest(mFlags.date);

    // Convert Slack ts (epoch.microseconds string) to ISO8601
    function tsToISO(ts) {
      if (!ts) return new Date().toISOString();
      return new Date(parseFloat(ts) * 1000).toISOString();
    }

    const wsId = await resolveWorkspace(globalFlags);
    const items = [];

    // --- 1. Fetch unread mentions from activity.feed ---
    try {
      const mentionTypes = 'at_user,at_user_group,at_channel,at_everyone,unjoined_channel_mention';
      const mentionData = await slackApi('activity.feed', {
        limit: String(mFlags.limit),
        types: mentionTypes,
        mode: 'chrono_reads_and_unreads',
        archive_only: 'false',
        unread_only: 'true',
        priority_only: 'false',
      }, wsId, { fatal: false });

      if (mentionData && mentionData.ok && mentionData.items) {
        for (const entry of mentionData.items) {
          const i = entry.item;
          // activity.feed at_user items: .item.message.{ts, channel, author_user_id}
          // NOTE: no .text or .thread_ts in the feed — must fetch the actual message for body
          const msg = i.message || {};
          const feedTs = entry.feed_ts;

          // Skip items older than the date cutoff
          if (feedTs && parseFloat(feedTs) < oldest) continue;

          const channelId = msg.channel || '';
          const authorId = msg.author_user_id || '';
          // msg.ts is the message ts; also the thread root ts if msg is in a thread
          const msgTs = msg.ts || feedTs || '';
          // thread_ts: if msg has thread_ts it's a reply, else msgTs is the root
          const threadTs = msg.thread_ts || msgTs;

          items.push({
            id: `slack-mention-${channelId}-${msgTs}`.replace(/\./g, ''),
            source: 'slack',
            type: 'mention',
            title: `Mention in ${channelId}`,
            subtitle: `#${channelId}`,
            url: `slack://channel/${channelId}/${msgTs ? 'p' + msgTs.replace('.', '') : ''}`,
            ts: tsToISO(feedTs || msgTs),
            body: '',  // filled by depth fetch below
            participants: authorId ? [authorId] : [],
            meta: { channel: channelId, thread_ts: threadTs, msg_ts: msgTs },
          });
        }
      }
    } catch (e) {
      // Non-fatal: continue with other sources
    }

    // --- 2. Fetch unread DM conversations ---
    try {
      // Get list of IM channels the user has
      const imList = await slackApi('conversations.list', {
        types: 'im',
        limit: '100',
        exclude_archived: 'true',
      }, wsId, { fatal: false });

      if (imList && imList.ok && imList.channels) {
        // Filter to channels with unread messages
        const unreadIms = imList.channels.filter(ch => ch.is_open || (ch.unread_count && ch.unread_count > 0));

        // Limit how many DMs we actually fetch history for
        const dmLimit = Math.min(unreadIms.length, 20);
        for (let idx = 0; idx < dmLimit; idx++) {
          const im = unreadIms[idx];
          try {
            const hist = await slackApi('conversations.history', {
              channel: im.id,
              limit: String(Math.max(1, mFlags.depth)),
              oldest: String(oldest),
            }, wsId, { fatal: false });

            if (hist && hist.ok && hist.messages && hist.messages.length > 0) {
              // One item per DM conversation — use the most recent message for metadata,
              // concatenate up to `depth` messages for body (most recent last)
              const msgs = hist.messages.slice(0, Math.max(1, mFlags.depth));
              const latestMsg = hist.messages[0];
              const userId = im.user || latestMsg.user || '';
              const msgTs = latestMsg.ts || '';
              const displayName = latestMsg.user_profile?.display_name || latestMsg.user_profile?.real_name || userId;
              // Reverse so oldest is first in body
              const body = msgs.slice().reverse().map(m => {
                const u = m.user_profile?.display_name || m.user_profile?.real_name || m.user || '';
                return `${u ? '@' + u + ': ' : ''}${(m.text || '').slice(0, 400)}`;
              }).join('\n\n').substring(0, 2000);

              const participants = [...new Set(msgs.map(m => m.user).filter(Boolean))];

              items.push({
                id: `slack-dm-${im.id}`,
                source: 'slack',
                type: 'dm',
                title: `DM from ${displayName}`,
                subtitle: `DM from @${displayName}`,
                url: `slack://channel/${im.id}/${msgTs ? 'p' + msgTs.replace('.', '') : ''}`,
                ts: tsToISO(msgTs),
                body,
                participants,
                meta: { channel: im.id, thread_ts: null },
              });
            }
          } catch (e) {
            // Skip this DM channel on error
          }
        }
      }
    } catch (e) {
      // Non-fatal: continue with other sources
    }

    // --- 3. Fetch thread replies from activity.feed ---
    try {
      const threadData = await slackApi('activity.feed', {
        limit: String(mFlags.limit),
        types: 'thread_v2',
        mode: 'chrono_reads_and_unreads',
        archive_only: 'false',
        unread_only: 'true',
        priority_only: 'false',
      }, wsId, { fatal: false });

      if (threadData && threadData.ok && threadData.items) {
        for (const entry of threadData.items) {
          const i = entry.item;
          const feedTs = entry.feed_ts;

          // Skip items older than the date cutoff
          if (feedTs && parseFloat(feedTs) < oldest) continue;

          // thread_v2 shape is undocumented — probe multiple known paths
          // Common shapes seen: i.message.{ts,channel}, i.subscription.{thread_ts,channel_id},
          // i.thread.{root_ts,channel}, i.channel + i.thread_ts
          const msg = i.message || {};
          const sub = i.subscription || {};
          const thr = i.thread || {};

          const channelId = msg.channel || sub.channel_id || thr.channel || i.channel || '';
          const authorId = msg.author_user_id || sub.user_id || '';
          // thread_ts is the root message — check all known paths
          const threadTs = msg.thread_ts || sub.thread_ts || thr.root_ts || i.thread_ts || msg.ts || feedTs || '';
          const msgTs = msg.ts || feedTs || '';

          if (!channelId) continue; // can't fetch without channel

          items.push({
            id: `slack-thread-${channelId}-${threadTs}`.replace(/\./g, ''),
            source: 'slack',
            type: 'thread',
            title: `Thread reply in ${channelId}`,
            subtitle: `#${channelId}`,
            url: `slack://channel/${channelId}/${threadTs ? 'p' + threadTs.replace('.', '') : ''}`,
            ts: tsToISO(feedTs || msgTs),
            body: '',  // filled by depth fetch below
            participants: authorId ? [authorId] : [],
            meta: { channel: channelId, thread_ts: threadTs, msg_ts: msgTs },
          });
        }
      }
    } catch (e) {
      // Non-fatal: continue
    }

    // --- Fetch full threads for depth > 0 ---
    if (mFlags.depth > 0) {
      // For each item that has a channel + thread_ts, pull conversations.replies.
      // For non-threaded mentions, thread_ts === msg_ts (the message itself is root).
      // conversations.replies with ts=root always returns the root + any replies.
      await Promise.all(items.map(async (item) => {
        const { channel, thread_ts } = item.meta || {};
        if (!channel || !thread_ts) return;
        if (item.source !== 'slack') return;
        if (item.type === 'dm') return; // DMs already have body from conversations.history
        try {
          const replies = await slackApi('conversations.replies', {
            channel,
            ts: thread_ts,
            limit: String(Math.min(mFlags.depth + 1, 100)), // +1 to include root
          }, wsId, { fatal: false });
          if (replies && replies.ok && replies.messages && replies.messages.length > 0) {
            const thread = replies.messages
              .map(m => {
                const user = m.user_profile?.display_name || m.user_profile?.real_name || m.user || '';
                return `${user ? '@' + user + ': ' : ''}${(m.text || '').slice(0, 400)}`;
              })
              .join('\n\n');
            item.body = thread;
            // Collect all participants from the thread
            const participants = new Set(item.participants);
            for (const m of replies.messages) {
              if (m.user) participants.add(m.user);
            }
            item.participants = [...participants];
          }
        } catch {
          // Non-fatal: keep original body
        }
      }));
    }

    // --- Deduplicate by id ---
    const seen = new Set();
    const unique = [];
    for (const item of items) {
      if (!seen.has(item.id)) {
        seen.add(item.id);
        unique.push(item);
      }
    }

    // --- Sort by ts descending ---
    unique.sort((a, b) => (b.ts > a.ts ? 1 : b.ts < a.ts ? -1 : 0));

    // --- Slice to limit ---
    const result = unique.slice(0, mFlags.limit);

    // --- Output ---
    console.log(JSON.stringify(result));
  },
};

// --- Attachment action helper ---
// Executes interactive message button actions (approve/deny) via chat.attachmentAction.
// Used for Slack Connect invite requests and workspace invite approvals.

async function executeAttachmentAction(wsId, channel, messageTs, actionName) {
  const tabId = await findSlackTab();

  // First, fetch the message to get the callback_id and attachment structure
  const hist = await slackApi('conversations.history', {
    channel,
    oldest: messageTs,
    latest: messageTs,
    inclusive: 'true',
    limit: '1',
  }, wsId);

  if (!hist.ok || !hist.messages?.length) {
    console.error(`Error: Message ${messageTs} not found in channel ${channel}.`);
    process.exit(1);
  }

  const msg = hist.messages[0];

  // Find the attachment with action buttons
  let targetAttachment = null;
  let targetAction = null;
  for (const att of (msg.attachments || [])) {
    if (!att.actions) continue;
    const action = att.actions.find(a => a.name === actionName);
    if (action) {
      targetAttachment = att;
      targetAction = action;
      break;
    }
  }

  if (!targetAttachment || !targetAction) {
    console.error(`Error: No "${actionName}" button found on message ${messageTs}.`);
    console.error('Available actions:', (msg.attachments || []).flatMap(a => (a.actions || []).map(act => act.name)).join(', ') || 'none');
    process.exit(1);
  }

  // Build the payload matching Slack's interactive message format
  const payload = JSON.stringify({
    actions: [targetAction],
    attachment_id: String(targetAttachment.id),
    callback_id: targetAttachment.callback_id,
    channel_id: channel,
    message_ts: messageTs,
    prompt_app_install: false,
  });

  // Execute via eval in the Slack tab (needs FormData, not URLSearchParams)
  const payloadJson = JSON.stringify(payload);
  const expr = `
(async () => {
  let token;
  try {
    const rawCfg = localStorage.getItem('localConfig_v2');
    const cfg = JSON.parse(rawCfg);
    if (!cfg || !cfg.teams || !cfg.teams['${wsId}'] || !cfg.teams['${wsId}'].token) {
      return JSON.stringify({ ok: false, error: 'token_not_found' });
    }
    token = cfg.teams['${wsId}'].token;
  } catch (e) {
    return JSON.stringify({ ok: false, error: 'token_not_found' });
  }
  const fd = new FormData();
  fd.append('token', token);
  fd.append('payload', ${payloadJson});
  fd.append('service_id', 'B01');
  fd.append('bot_user_id', 'USLACKBOT');
  fd.append('client_token', 'web-' + Date.now());
  return new Promise((resolve) => {
    const xhr = new XMLHttpRequest();
    xhr.open('POST', '/api/chat.attachmentAction', true);
    xhr.withCredentials = true;
    xhr.onload = () => resolve(xhr.responseText);
    xhr.onerror = () => resolve(JSON.stringify({ ok: false, error: 'xhr_error' }));
    xhr.send(fd);
  });
})()
  `;

  const data = await evalInSlackTab(expr);

  if (!data.ok) {
    console.error(`Error: ${data.error}`);
    process.exit(1);
  }

  const verb = actionName === 'approve' ? 'Approved' : 'Denied';
  const text = (msg.text || '').substring(0, 150).replace(/\n/g, ' ');
  console.log(`${verb}: ${text}`);
  console.log(`  Message: ${messageTs} in ${channel}`);
  console.log(`  Callback: ${targetAttachment.callback_id}`);
}

// --- Watch state helpers ---

async function loadAllWatchStates() {
  const globResult = await exec('ls /workspace/skills/slack/.watch-*.json 2>/dev/null');
  if (globResult.exitCode !== 0 || !globResult.stdout.trim()) return [];
  const files = globResult.stdout.trim().split('\n');
  const states = [];
  for (const file of files) {
    try {
      states.push(JSON.parse(await fs.readFile(file.trim(), 'utf8')));
    } catch (_) {}
  }
  return states;
}

// --- WebSocket interceptor injection ---
// Uses window.__slackWatchWatches as a mutable list so the watch set can be
// updated without re-wrapping already-intercepted WebSocket connections.

async function injectWsInterceptor(watchStates) {
  const tabId = await findSlackTab();

  // Build watch config as JSON for injection
  const watchConfig = watchStates.map(s => ({
    watchId: s.watchId,
    channel: s.channel,
    thread_ts: s.thread_ts,
    webhookUrl: s.webhookUrl,
    scoop: s.scoop,
  }));

  const interceptorCode = `
(async () => {
  // Update the mutable watch list on window — existing wrapped connections
  // read from this list on every message, so changes take effect immediately.
  window.__slackWatchWatches = ${JSON.stringify(watchConfig)};

  // Only install the WebSocket interceptor once
  if (window.__slackWatchInstalled) return 'watches_updated';

  function wrapConnection(ws) {
    if (ws.__slackWatchWrapped) return;
    ws.__slackWatchWrapped = true;

    const origOnMessage = ws.onmessage;
    ws.onmessage = function(event) {
      if (origOnMessage) origOnMessage.call(ws, event);

      try {
        const data = JSON.parse(event.data);
        if (data.type !== 'message') return;

        // Read the current watch list from window at dispatch time
        const watches = window.__slackWatchWatches || [];
        for (const w of watches) {
          if (data.channel !== w.channel) continue;
          if (w.thread_ts && data.thread_ts !== w.thread_ts) continue;

          const payload = {
            type: 'slack-watch',
            watchId: w.watchId,
            channel: data.channel,
            thread_ts: w.thread_ts,
            ts: data.ts,
            user: data.user,
            text: data.text,
            subtype: data.subtype || null,
            event: data,
          };

          fetch(w.webhookUrl, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(payload),
          }).catch(() => {});
        }
      } catch (_) {}
    };
  }

  // Patch WebSocket.prototype.send to discover existing connections
  const origSend = WebSocket.prototype.send;
  WebSocket.prototype.send = function(data) {
    wrapConnection(this);
    return origSend.call(this, data);
  };

  window.__slackWatchInstalled = true;

  // Slack sends ping keepalives every ~10s, so existing connections
  // are discovered within one ping cycle.

  return 'interceptor_installed';
})()
  `.trim().replace(/\n/g, ' ');

  const tmpFile = '/shared/.slack_ws_intercept_' + Date.now() + '.js';
  await fs.writeFile(tmpFile, interceptorCode);
  const result = await exec(`playwright-cli eval-file ${tmpFile} --tab=${tabId}`);
  await fs.rm(tmpFile).catch(async () => {
    await fs.writeFile(tmpFile, '').catch(() => {});
  });

  if (result.exitCode !== 0) {
    throw new Error(result.stderr || 'eval failed');
  }
}

// --- Main ---

const rawArgs = process.argv.slice(2);

// Extract global flags (--workspace, --ws) before command dispatch
const globalFlags = {};
const filteredArgs = [];
for (let i = 0; i < rawArgs.length; i++) {
  const arg = rawArgs[i];
  if (arg.startsWith('--workspace=')) {
    const val = arg.slice('--workspace='.length);
    if (!val) { console.error('Error: --workspace requires a non-empty workspace ID.'); process.exit(1); }
    globalFlags.workspace = val;
  } else if (arg.startsWith('--ws=')) {
    const val = arg.slice('--ws='.length);
    if (!val) { console.error('Error: --ws requires a non-empty workspace ID.'); process.exit(1); }
    globalFlags.workspace = val;
  } else if (arg === '--workspace' || arg === '--ws') {
    const val = rawArgs[++i];
    if (!val) { console.error(`Error: ${arg} requires a non-empty workspace ID.`); process.exit(1); }
    globalFlags.workspace = val;
  } else {
    filteredArgs.push(arg);
  }
}
const [cmd, ...args] = filteredArgs;

if (!cmd || cmd === 'help' || cmd === '--help') {
  console.log('Slack API client — interact with Slack from the command line.\n');
  console.log('Usage: slack [--workspace=<ID>] <command> [args]\n');
  console.log('Global flags:');
  console.log('  --workspace=<ID>, --ws=<ID>              Use a specific workspace (team/enterprise ID)');
  console.log('                                           Auto-detects from active Slack tab if omitted\n');
  console.log('Commands:');
  console.log('  workspaces                               List all available workspaces');
  console.log('  activity [--type=TYPE] [--unread] [--limit=N] [--cursor=CURSOR]');
  console.log('                                           View activity feed (notifications)');
  console.log('           Types: all, admin, mentions, threads, reactions, invites, apps');
  console.log('  pending [--pages=N] [--json]             List pending approval requests');
  console.log('  approve <message_ts> [--channel=<id>]    Approve an interactive action (e.g. invite request)');
  console.log('  deny <message_ts> [--channel=<id>]       Deny an interactive action (e.g. invite request)');
  console.log('  history <channel_id> [--limit=N]          Read channel messages');
  console.log('  post <id> <message> [--thread_ts=TS]      Post a message to any channel, DM, or user');
  console.log('  channels --search=<term>                  Search for channels');
  console.log('  thread <channel_id> <thread_ts> [--limit] Read thread replies');
  console.log('  user <user_id>                            Look up user info');
  console.log('  info <channel_id>                         Get channel info');
  console.log('  slackbot                                  Find Slackbot DM channel');
  console.log('  watch <channel_id> --scoop=<name>         Watch channel for new messages');
  console.log('  unwatch <channel_id> [--thread=<ts>]      Stop watching a channel');
  console.log('  watches                                   List active watches');
  console.log('  reinject                                  Re-inject WebSocket interceptor');
  console.log('  monday [--limit=N] [--depth=N] [--date=Nd] Monday protocol: fetch inbox as JSON');
  console.log(`\nUse "slack workspaces" to list available workspaces and their IDs.`);
  console.log(`Use "slack slackbot" to find your Slackbot DM channel ID.`);
  process.exit(0);
}

if (!commands[cmd]) {
  console.error(`Unknown command: ${cmd}`);
  console.error('Run "slack help" for usage.');
  process.exit(1);
}

const result = await commands[cmd](args, globalFlags);
